import '../models/user_model.dart';
import '../models/reminder_model.dart';

class MockDataService {
  static UserModel currentUser = UserModel(
    uid: 'mock_user_123',
    name: 'Alex Morgan',
    email: 'alex.morgan@example.com',
    phone: '+14155552671',
    timezone: 'Asia/Kolkata',
    preferredLanguage: 'English',
    createdAt: DateTime.now().subtract(const Duration(days: 30)),
    updatedAt: DateTime.now(),
  );

  static List<ReminderModel> sampleReminders = [
    ReminderModel(
      id: 'rem_101',
      userId: 'mock_user_123',
      title: 'Submit project report',
      notes: 'Submit final PDF report to project coordinator.',
      scheduledAt: DateTime.now().add(const Duration(minutes: 45)),
      timezone: 'Asia/Kolkata',
      reminderType: ReminderType.aiCall,
      repeatType: 'Never',
      language: 'English',
      status: ReminderStatus.scheduled,
      retryEnabled: true,
      retryDelayMinutes: 10,
      createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      updatedAt: DateTime.now().subtract(const Duration(hours: 2)),
    ),
    ReminderModel(
      id: 'rem_102',
      userId: 'mock_user_123',
      title: 'Take evening medicine',
      notes: 'Take 1 tablet after food.',
      scheduledAt: DateTime.now().add(const Duration(hours: 4)),
      timezone: 'Asia/Kolkata',
      reminderType: ReminderType.aiCall,
      repeatType: 'Daily',
      language: 'English',
      status: ReminderStatus.scheduled,
      retryEnabled: true,
      retryDelayMinutes: 5,
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    ReminderModel(
      id: 'rem_103',
      userId: 'mock_user_123',
      title: 'Call Client regarding contract renewal',
      notes: 'Discuss Q3 deliverables and SLA adjustments.',
      scheduledAt: DateTime.now().subtract(const Duration(minutes: 15)),
      timezone: 'Asia/Kolkata',
      reminderType: ReminderType.aiCall,
      repeatType: 'Never',
      language: 'English',
      status: ReminderStatus.calling,
      retryEnabled: true,
      retryDelayMinutes: 10,
      createdAt: DateTime.now().subtract(const Duration(hours: 1)),
      updatedAt: DateTime.now().subtract(const Duration(minutes: 2)),
      lastCallAt: DateTime.now().subtract(const Duration(minutes: 2)),
    ),
    ReminderModel(
      id: 'rem_104',
      userId: 'mock_user_123',
      title: 'Morning team standup call',
      notes: 'Review pull requests and sprint backlog.',
      scheduledAt: DateTime.now().subtract(const Duration(hours: 3)),
      timezone: 'Asia/Kolkata',
      reminderType: ReminderType.aiCall,
      repeatType: 'Daily',
      language: 'English',
      status: ReminderStatus.completed,
      completedAt: DateTime.now().subtract(const Duration(hours: 3)),
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      updatedAt: DateTime.now().subtract(const Duration(hours: 3)),
    ),
    ReminderModel(
      id: 'rem_105',
      userId: 'mock_user_123',
      title: 'Pay electricity bill',
      notes: 'Due date today before midnight.',
      scheduledAt: DateTime.now().subtract(const Duration(hours: 5)),
      timezone: 'Asia/Kolkata',
      reminderType: ReminderType.aiCall,
      repeatType: 'Never',
      language: 'Hindi',
      status: ReminderStatus.missed,
      retryEnabled: true,
      retryDelayMinutes: 30,
      retryCount: 2,
      createdAt: DateTime.now().subtract(const Duration(hours: 6)),
      updatedAt: DateTime.now().subtract(const Duration(hours: 5)),
      lastCallAt: DateTime.now().subtract(const Duration(hours: 5)),
    ),
  ];
}
